/** Admin copy (01 §M12). */
export const adminCopy = {
  title: 'Admin',
  intro: 'Installed packs, thresholds, agent and model settings, and demo snapshots. Settings come from the server environment; secrets are never shown.',
  packs: 'Packs',
  pack: 'Pack',
  version: 'Version',
  depth: 'Depth',
  contents: 'Contents',
  rubrics: 'Rubric thresholds',
  agents: 'Agent mode & models',
  defaultMode: 'Default agent mode',
  key: 'Anthropic API key',
  present: 'Present',
  absent: 'Absent',
  model: (k: string) => `Model (${k})`,
  notSet: 'not set',
  budgets: 'Budgets',
  timeout: 'Live answer timeout (ms)',
  rounds: 'Max tool rounds',
  sessionBudget: 'Session budget (USD)',
  scale: 'Data scale',
  snapshots: 'Snapshots',
  none: 'No snapshots yet — saving a Demo Profile takes one.',
  restricted: 'Admin is for the data steward (persona D) or the presenter.',
};
