/** Admin copy (01 §M12). */
export const adminCopy = {
  title: 'Admin',
  intro: 'Installed packs, thresholds, agent and model settings, and demo snapshots. Settings come from the server environment; secrets are never shown.',
  packs: 'Packs',
  pack: 'Pack',
  version: 'Version',
  depth: 'Depth',
  contents: 'Contents',
  rubrics: 'Rubric thresholds',
  agents: 'Agent mode & models',
  defaultMode: 'Default agent mode',
  key: 'Anthropic API key',
  present: 'Present',
  absent: 'Absent',
  model: (k: string) => `Model (${k})`,
  notSet: 'not set',
  budgets: 'Budgets',
  timeout: 'Live answer timeout (ms)',
  rounds: 'Max tool rounds',
  sessionBudget: 'Session budget (USD)',
  scale: 'Data scale',
  snapshots: 'Snapshots',
  none: 'No snapshots yet — saving a Demo Profile takes one.',
  restricted: 'Admin is for the data steward (persona D) or the presenter.',
  drafter: {
    title: 'Pack Drafter',
    intro: 'Create a Draft pack for an industry not covered by cloning the nearest deep pack and re-skinning it (company, code, regions). Drafts are badged and stay out of stories until a human reviews them and approves golden answers.',
    from: 'Start from',
    id: 'Pack id',
    code: 'Code (2–4 letters)',
    name: 'Pack name',
    industry: 'Industry',
    company: 'Fictional company',
    short: 'Short name',
    hq: 'Headquarters town',
    regions: 'Regions (comma-separated)',
    submit: 'Draft pack',
    working: 'Drafting and validating…',
    liveNote: 'Live drafting (an LLM writing each section under the pack schema) needs an API key; offline cloning is always available.',
  },
};
