/** Agent Factory copy (split from en.ts to keep files under 600 lines). */
export const factoryCopy = {
  title: 'Agent Factory',
  intro: 'Compose a governed agent from certified products, evaluate it, pass the publish gate and release it.',
  newAgent: 'New agent',
  noAgents: 'No factory agents yet.',
  steps: ['Purpose', 'Ground it', 'Instructions', 'Tools & budgets', 'Evaluate', 'Publish gate', 'Release'],
  name: 'Agent name',
  capability: 'Capability (one sentence)',
  personaServed: 'Persona served',
  decisions: 'Decisions it supports (one per line)',
  products: 'Certified products',
  notCertified: 'not certified — cannot be bound',
  kpis: 'KPIs (coverage proposed from the products’ semantic views)',
  grains: 'grains',
  slices: 'slices',
  design: 'Draft with Agent Designer',
  instruction: { persona: 'Persona', response: 'Response', guardrail: 'Guardrail', orchestration: 'Orchestration' },
  outOfScope: 'Out of scope (one per line)',
  rowLimit: 'Row limit',
  cost: 'Cost per answer budget (USD)',
  latency: 'p95 latency budget (ms)',
  rounds: 'Max tool rounds',
  onCall: 'On call',
  save: 'Save',
  saved: 'Saved',
  runEval: 'Run evaluation (scripted)',
  suite: 'Suite',
  score: 'Score',
  threshold: 'Threshold',
  cases: 'cases',
  failing: 'Failing cases',
  runGate: 'Run publish gate',
  approvePilot: 'Approve release to Pilot',
  promoteCanary: 'Promote to Canary (20%)',
  promoteProduction: 'Promote to Production',
  rollback: 'Roll back to Pilot',
  rationale: 'Rationale',
  status: 'Status',
  version: 'Version',
  openAsk: 'Ask this agent',
} as const;
