/** Run (operate) copy: Health, Agent Quality, Cost & Value, Impact, Audit. */
export const operateCopy = {
  health: {
    title: 'Health',
    intro: 'Freshness, volume, quality and schema signals for every data product, and the incidents behind them.',
    tabs: { board: 'Health board', incidents: 'Incidents' },
    product: 'Product',
    status: 'Status',
    freshness: 'Freshness',
    volume: 'Volume',
    quality: 'Quality',
    schema: 'Schema',
    dq: 'DQ score',
    breakTitle: 'Break something',
    breakIntro: 'Open a scripted incident. Its effects flow through the governed query path: affected products degrade and agent answers carry an incident banner.',
    breakIt: 'Break',
    open: 'Open incidents',
    none: 'No incidents yet.',
    resolve: 'Resolve',
    blast: 'Blast radius',
    postmortem: 'Postmortem',
    ttd: 'Time to detect',
    ttr: 'Time to resolve',
    minutes: 'min',
    detection: 'Detection',
    impact: 'Impact',
    resolution: 'Resolution',
    actions: 'Follow-up actions',
    opened: 'Opened',
    resolved: 'Resolved',
    signal: { ok: 'OK', warn: 'Warning', fail: 'Failing' },
    state: { healthy: 'Healthy', degraded: 'Degraded', down: 'Down' },
  },
  quality: {
    title: 'Agent Quality',
    intro: 'Eval scorecards per agent, the feedback inbox and fixes that write versioned context.',
    tabs: { scorecards: 'Scorecards', feedback: 'Feedback inbox' },
    agent: 'Agent',
    score: 'Quality',
    harness: 'Harness',
    runs: 'Eval runs',
    fixes: 'Fixes',
    runEval: 'Run eval',
    noEval: 'Not evaluated yet',
    calibrated: 'Calibrated by the pack for the quality story; the “after” value appears only once the fix resolves the feedback question.',
    inboxEmpty: 'No thumbs-down feedback.',
    question: 'Question',
    reason: 'Reason',
    state: 'State',
    applyScripted: 'Apply suggested fix',
    applyCustom: 'Add synonym fix',
    term: 'Term the user said',
    synonymsOf: 'Means (metric)',
    dismiss: 'Dismiss',
    fixed: (before: number, after: number) => `Fix applied as a versioned context entry. Eval ${before}% → ${after}%.`,
  },
  cost: {
    title: 'Cost & Value',
    intro: 'Illustrative monthly run cost by layer, product and agent, with what-if levers — and the value each product is expected to deliver.',
    illustrative: 'Illustrative: placeholder rates and credit price, not a quote.',
    tabs: { cost: 'Cost', value: 'Value' },
    levers: 'What-if levers',
    lagFactor: 'Refresh lag (× target lag)',
    warehouse: 'Warehouse size',
    questions: 'Agent questions per day',
    creditPrice: 'Credit price (USD)',
    apply: 'Recalculate',
    reset: 'Defaults',
    total: 'Monthly total',
    byDriver: 'By driver',
    byLayer: 'By layer',
    byProduct: 'By product',
    byAgent: 'By agent',
    freshness: 'Freshness',
    sla: 'SLA',
    breach: 'SLA breached',
    perConsumer: 'Per consumer',
    perQuestion: 'Per question',
    live: 'Live-mode actuals (tokens and illustrative cost from answers)',
    noLive: 'No live-mode answers yet — actuals appear once an agent answers in live mode.',
    hypothesis: 'Hypothesis',
    annual: 'Expected / year',
    measured: 'Measured',
    annualCost: 'Run cost / year',
    roi: 'Value ÷ cost',
    portfolio: 'Portfolio',
  },
  impact: {
    title: 'Impact',
    intro: 'Pick an object or column and a change to see everything downstream, the severity and a change plan.',
    object: 'Object',
    column: 'Column (optional)',
    change: 'Change',
    changes: { rename: 'Rename', drop: 'Drop', type_change: 'Type change', add: 'Add column', delay: 'Delivery delay' },
    analyse: 'Analyse',
    severity: 'Severity',
    bump: 'Contract version bump',
    notice: 'Notice period',
    days: 'days',
    downstream: 'Downstream',
    objects: 'Objects',
    metrics: 'Metrics',
    kpis: 'KPIs',
    products: 'Products',
    agents: 'Agents',
    consumers: 'Consumers',
    plan: 'Change plan',
    pick: 'Choose an object to analyse.',
  },
  audit: {
    title: 'Audit & Lineage',
    intro: 'The append-only, hash-chained event stream and the full-estate lineage.',
    tabs: { stream: 'Event stream', lineage: 'Lineage' },
    chainOk: (n: number) => `Hash chain verified across ${n} events.`,
    chainBroken: (at: string) => `Hash chain broken at ${at}.`,
    actorType: 'Actor type',
    subject: 'Subject',
    all: 'All',
    filter: 'Filter',
    when: 'When',
    actor: 'Actor',
    action: 'Action',
    export: 'Export audit bundle',
    showing: (n: number, total: number) => `Showing ${n} of ${total} events.`,
  },
};
