/** Presenter copy: overlay, profile setup, story print. */
export const presenterCopy = {
  title: 'Presenter',
  open: 'Presenter',
  close: 'Close presenter',
  story: 'Story',
  go: 'Go',
  cue: 'Cue card',
  doThis: 'Do this',
  tryThis: 'Try this',
  sayThis: 'Say this',
  next: 'Next',
  stepTime: 'Step',
  totalTime: 'Total',
  reset: 'Reset demo',
  confirmReset: 'Confirm reset',
  breakIt: 'Break something',
  fixIt: 'Fix it',
  leaveBehind: 'Leave-behind mode',
  print: 'Print cue cards',
  shortcuts: 'Shift+P toggles · Shift+→ next step · Shift+← previous step',
  freeRoam: 'Free roam',
  profile: {
    setup: 'Profile setup',
    name: 'Profile name',
    company: 'Company display name',
    productName: 'Product name',
    logo: 'Logo (PNG or SVG, ≤ 200 KB)',
    primary: 'Primary colour',
    accent: 'Accent colour',
    contrastOk: 'Meets WCAG AA',
    contrastFail: (s: string) => `Fails WCAG AA — try ${s}`,
    terms: 'Terminology overrides (display only)',
    story: 'Story',
    agentMode: 'Agent mode',
    liveDisabled: 'Live needs an API key on the server; Auto falls back to scripted.',
    lock: 'Lock to this profile (kiosk)',
    save: 'Save profile',
    saved: 'Saved profiles',
    none: 'No saved profiles yet.',
    launch: 'Launch',
    duplicate: 'Duplicate',
    archive: 'Archive',
    export: 'Export',
    import: 'Import profile',
    importFile: 'Profile file (.keystone-profile.json)',
    lastUsed: 'last used',
    never: 'never',
    locked: 'This demo is locked to a profile.',
    backToDemo: 'Back to the demo',
  },
  printPage: { title: 'Cue cards', step: 'Step', persona: 'Persona', route: 'Screen' },
};
