/** Strategy copy: Platform Map, Why AI-Ready (Knockout, Compare), Readiness, Roadmap, Portfolio, Operating Model. */
export const strategyCopy = {
  layers: { silver: 'Silver', gold: 'Gold', semantic: 'Semantic', glossary: 'Glossary', context: 'Context', governance: 'Governance' },
  failure: { wrong: 'Wrong', unsafe: 'Unsafe', ambiguous: 'Ambiguous', unverified: 'Unverified' },
  confidence: { trusted: 'Trusted', questionable: 'Questionable', unsafe: 'Unsafe' },
  knockout: {
    title: 'Why AI-Ready — Knockout',
    intro: 'Switch layers off and watch four governed answers degrade. Every number below is recomputed through the governed query path with that layer removed.',
    switches: 'Layers',
    apply: 'Recompute',
    allOn: 'All layers on',
    governed: 'Governed answer',
    now: 'With layers off',
    delta: 'Change',
    failures: 'Failure',
    notComputable: 'Not computable',
    sql: 'Query that ran',
    none: '—',
  },
  compare: {
    title: 'Why AI-Ready — Compare',
    intro: 'The same question answered over the raw stack (every layer off) and over the governed stack.',
    question: 'Question',
    raw: 'Raw stack',
    governed: 'Governed stack',
    scorecard: 'Scorecard',
    rules: 'Business rules applied',
    certified: 'Certified source',
    policies: 'Policies enforced',
    yes: 'Yes',
    no: 'No',
  },
  readiness: {
    title: 'AI Readiness',
    intro: 'Twenty-one questions across seven dimensions. Pick a preset or answer live with the client; scores, the band and ranked gaps update on submit.',
    presets: 'Presets',
    score: 'Score',
    overall: 'Overall',
    band: 'Band',
    gaps: 'Ranked gaps',
    actions: 'Recommended actions',
    target: 'Target',
    calculate: 'Score',
    save: 'Save assessment',
    name: 'Assessment name',
    saved: 'Saved assessments',
    noneSaved: 'No saved assessments yet.',
    radar: 'Readiness by dimension',
    unanswered: 'Answer every question to see the overall score.',
    roadmap: 'Generate roadmap from these gaps',
  },
  roadmap: {
    title: 'Roadmap',
    intro: 'Seven phases with gates and workstreams, generated from the readiness gaps. The highlighted phases close the three largest gaps.',
    youAreHere: 'You are here',
    source: 'Generated from',
    weeks: 'weeks',
    gate: 'Exit gate',
    proof: 'Proof',
    deliverables: 'Deliverables',
    risks: 'Risks',
    roles: 'Roles',
    workstream: 'Workstream',
    start: 'Start',
    planView: 'Plan',
    coverageView: 'Coverage',
    simulate: 'Simulate +4 weeks',
    phaseLabel: 'phase',
    level: 'Level',
    sourceTable: 'Source table',
    blocker: 'Next blocker',
  },
  portfolio: {
    title: 'Portfolio',
    intro: 'Every product by lifecycle phase, prioritised by an advisory score a named human can override with a reason — with cost, adoption and value beside it.',
    pipeline: 'Pipeline by phase',
    ranking: 'Prioritisation',
    model: 'Model',
    rank: 'Rank',
    product: 'Product',
    phase: 'Phase',
    score: 'Score',
    why: 'Why',
    cost: 'Run cost / month',
    adoption: 'Answers',
    value: 'Value (expected / realised)',
    override: 'Override',
    overrideScore: 'New score',
    reason: 'Reason',
    overridden: (by: string, reason: string) => `Overridden by ${by}: ${reason}`,
    maturity: 'Capability maturity',
    maturityIntro: 'Each level is derived from evidence in the live estate, so it moves when the estate does.',
    evidence: 'Evidence',
    next: 'Next move',
    sizing: 'Sizing: 40 people per consumer group; 6 build days per upstream object (illustrative).',
  },
  operating: {
    title: 'Operating Model',
    intro: 'Who is responsible and accountable for each activity, by operating style.',
    style: 'Operating style',
    roles: 'Roles',
    activity: 'Activity',
    legend: 'R responsible · A accountable · C consulted · I informed',
  },
  platform: {
    title: 'Platform Map',
    intro: 'The nine layers of an AI-ready estate for this company: what each holds and what breaks without it.',
    holds: 'Holds',
    breaks: 'What breaks without it',
    nothing: 'Nothing in the four knockout answers depends on this layer alone.',
    replay: 'Replay the flow',
    flow: 'One governed answer, end to end',
    path: 'Guided path',
    steps: ['Explore the raw and conformed data', 'See the metric defined once', 'Find the certified product', 'Ask the agent', 'Watch it run'],
    more: (n: number) => `and ${n} more`,
  },
};
