/**
 * Generic UI copy (English). Industry-specific strings never live here — they come from the active pack.
 * Product name is white-label: read it from the active brand, never from this file.
 */
export const copy = {
  doors: {
    home: 'Home',
    consume: 'Consume',
    build: 'Build',
    run: 'Run',
    strategy: 'Strategy',
  },
  nav: {
    home: 'Home',
    marketplace: 'Marketplace',
    ask: 'Ask an Agent',
    access: 'My Access',
    request: 'Request a Product',
    studio: 'Product Studio',
    factory: 'Agent Factory',
    explorer: 'Explorer',
    semantic: 'Semantic',
    glossary: 'Glossary',
    context: 'Context',
    health: 'Health',
    agentQuality: 'Agent Quality',
    costValue: 'Cost & Value',
    impact: 'Impact',
    audit: 'Audit & Lineage',
    platformMap: 'Platform Map',
    knockout: 'Knockout',
    compare: 'Compare',
    readiness: 'Readiness',
    roadmap: 'Roadmap',
    portfolio: 'Portfolio',
    operatingModel: 'Operating Model',
    admin: 'Admin',
  },
  navDetail: {
    productDetail: 'Data product',
    agentDetail: 'Agent',
    requestDetail: 'Product request',
    studioWorkspace: 'Product workspace',
    factoryDraft: 'Agent draft',
  },
  shell: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary',
    packSwitcher: 'Switch industry pack',
    searchPlaceholder: 'Search',
    searchShortcut: '/',
    paletteShortcut: 'Ctrl K',
    persona: 'Persona',
    personaHeading: 'View the demo as…',
    personaNowViewing: 'Now viewing as',
    personaArchetype: 'Archetype',
    presenterMenu: 'Presenter menu',
    presenterPending: 'Presenter tools arrive in Phase 9.',
    footer: 'Synthetic demo data',
    asOf: 'as of',
    modes: { scripted: 'Scripted', live: 'Live', auto: 'Auto' },
    modeLabel: 'Agent mode',
  },
  stub: {
    eyebrow: 'Coming in phase',
    module: 'Module',
    spec: 'Specification',
    params: 'Route parameters',
    none: 'none',
    body: 'This screen is scaffolded. Its behaviour and acceptance criteria are defined in the specification and land in the phase shown.',
  },
  launcher: {
    title: 'Demo launcher',
    subtitle: 'Pick an industry pack, brand it for the client and choose a story.',
    noPacks: 'No industry packs are installed yet.',
    noPacksHint: 'Add a pack under packs/ and run pnpm warehouse:build.',
    open: 'Open',
    products: 'data products',
    agents: 'agents',
    kpis: 'KPIs',
    depth: { deep: 'Deep', standard: 'Standard', draft: 'Draft' },
  },
  explorer: {
    title: 'Explorer',
    intro: 'Browse every layer of the warehouse. Every preview and worksheet result goes through the governed query path, so what you see depends on who you are.',
    tree: 'Objects',
    worksheet: 'Worksheet',
    tabs: { preview: 'Preview', columns: 'Columns', ddl: 'DDL', lineage: 'Lineage', quality: 'Quality', governance: 'Governance' },
    rows: 'rows',
    masked: 'masked',
    rowFiltered: 'Row filter applied',
    noRows: 'No rows.',
    column: 'Column',
    type: 'Type',
    nullable: 'Nullable',
    tags: 'Tags',
    term: 'Glossary term',
    masking: 'Masking for you',
    clear: 'Clear',
    pendingFix: 'Masking not attached yet',
    noRules: 'No data quality rules are declared for this object.',
    qualityPhase: 'Rule results and scores arrive with the quality engine (Phase 5). Declared rules:',
    rule: 'Rule',
    dimension: 'Dimension',
    assertion: 'Assertion',
    severity: 'Severity',
    products: 'Data products using this object',
    policies: 'Policies',
    grants: 'Personas entitled',
    history: 'Recent governed access',
    noHistory: 'No governed queries yet.',
    persona: 'Persona',
    purpose: 'Purpose',
    when: 'When',
    upstream: 'Upstream',
    downstream: 'Downstream',
    run: 'Run',
    running: 'Running…',
    presets: 'Presets',
    sqlLabel: 'SQL (read-only SELECT)',
    worksheetIntro: 'Read-only SELECT queries run with your persona’s masking and row filters. Statements that change data are rejected before they run.',
    emptySchema: 'No objects in this schema.',
    displaySql: 'Executed as (Snowflake dialect)',
  },
  semantic: {
    title: 'Semantic views',
    intro: 'Metrics are defined once, here. Every number on every screen — and every agent answer — is compiled from these definitions.',
    metrics: 'metrics',
    tabs: { model: 'Model', metrics: 'Metrics', dimensions: 'Dimensions', verified: 'Verified queries', yaml: 'YAML', playground: 'Playground' },
    tables: 'Tables',
    dimensions: 'Dimensions',
    timeDimensions: 'Time dimensions',
    facts: 'Facts',
    name: 'Name',
    expression: 'Expression',
    unit: 'Unit',
    synonyms: 'Synonyms',
    term: 'Term',
    rules: 'Default rules',
    question: 'Question',
    status: 'Status',
    verifiedBy: 'Verified by',
    products: 'Published by',
    metric: 'Metric',
    by: 'By',
    grain: 'Time grain',
    range: 'Time range',
    filter: 'Filter',
    value: 'Value',
    none: 'None',
    runQuery: 'Run',
    askAgent: 'Ask an agent this',
    generatedSql: 'Generated SQL (Snowflake dialect)',
    ranges: { none: 'All time', 'last-month': 'Last month', 'last-quarter': 'Last quarter', 'last-4-quarters': 'Last 4 quarters', ytd: 'Year to date', 'last-year': 'Last year' },
    rulesApplied: 'Business rules applied',
    pickMetric: 'Pick a metric and press Run.',
  },
  glossary: {
    title: 'Business glossary',
    intro: 'Every governed term, its owner and where it lives — columns, metrics, products and agents.',
    search: 'Filter terms',
    term: 'Term',
    definition: 'Definition',
    formula: 'Formula',
    owner: 'Owner',
    steward: 'Steward',
    status: 'Status',
    cde: 'Critical data element',
    synonyms: 'Synonyms',
    mappings: 'Where it lives',
    columns: 'Columns',
    metrics: 'Metrics',
    products: 'Data products',
    agents: 'Agents',
    dq: 'Data quality rules on mapped columns',
    noDq: 'No DQ rules on the mapped columns.',
  },
  context: {
    title: 'Context',
    intro: 'What agents know beyond the data: instructions, business rules, verified queries, synonyms and policy documents.',
    tabs: { instructions: 'Instructions', rules: 'Business rules', verified: 'Verified queries', synonyms: 'Synonyms', documents: 'Documents' },
    agent: 'Agent',
    kind: 'Type',
    version: 'Version',
    rule: 'Rule',
    applies: 'Machine-applied filter',
    source: 'Source document',
    searchDocs: 'Search documents',
    noHits: 'No matching passages.',
    injection: 'Contains planted prompt-injection text (adversarial testing)',
    term: 'Term',
    synonyms: 'Synonyms',
    mapsTo: 'Maps to',
    search: 'Search',
  },
  outcome: {
    denied: 'Access needed',
    rejected: 'Query not run',
    unavailable: 'Not available yet',
    request: 'Request access',
  },
  errors: {
    notFoundTitle: 'Nothing here',
    notFoundBody: 'This page does not exist in the current demo.',
    backToLauncher: 'Back to the launcher',
  },
} as const;

export type Copy = typeof copy;
