/**
 * Generic UI copy (English). Industry-specific strings never live here — they come from the active pack.
 * Product name is white-label: read it from the active brand, never from this file.
 */
export const copy = {
  doors: {
    home: 'Home',
    consume: 'Consume',
    build: 'Build',
    run: 'Run',
    strategy: 'Strategy',
  },
  nav: {
    home: 'Home',
    marketplace: 'Marketplace',
    ask: 'Ask an Agent',
    access: 'My Access',
    request: 'Request a Product',
    studio: 'Product Studio',
    factory: 'Agent Factory',
    explorer: 'Explorer',
    semantic: 'Semantic',
    glossary: 'Glossary',
    context: 'Context',
    health: 'Health',
    agentQuality: 'Agent Quality',
    costValue: 'Cost & Value',
    impact: 'Impact',
    audit: 'Audit & Lineage',
    platformMap: 'Platform Map',
    knockout: 'Knockout',
    compare: 'Compare',
    readiness: 'Readiness',
    roadmap: 'Roadmap',
    portfolio: 'Portfolio',
    operatingModel: 'Operating Model',
    admin: 'Admin',
  },
  navDetail: {
    productDetail: 'Data product',
    agentDetail: 'Agent',
    requestDetail: 'Product request',
    studioWorkspace: 'Product workspace',
    factoryDraft: 'Agent draft',
  },
  shell: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary',
    packSwitcher: 'Switch industry pack',
    searchPlaceholder: 'Search',
    searchShortcut: '/',
    paletteShortcut: 'Ctrl K',
    persona: 'Persona',
    personaHeading: 'View the demo as…',
    personaNowViewing: 'Now viewing as',
    personaArchetype: 'Archetype',
    presenterMenu: 'Presenter menu',
    presenterPending: 'Presenter tools arrive in Phase 9.',
    footer: 'Synthetic demo data',
    asOf: 'as of',
    modes: { scripted: 'Scripted', live: 'Live', auto: 'Auto' },
    modeLabel: 'Agent mode',
  },
  stub: {
    eyebrow: 'Coming in phase',
    module: 'Module',
    spec: 'Specification',
    params: 'Route parameters',
    none: 'none',
    body: 'This screen is scaffolded. Its behaviour and acceptance criteria are defined in the specification and land in the phase shown.',
  },
  launcher: {
    title: 'Demo launcher',
    subtitle: 'Pick an industry pack, brand it for the client and choose a story.',
    noPacks: 'No industry packs are installed yet.',
    noPacksHint: 'Add a pack under packs/ and run pnpm warehouse:build.',
    open: 'Open',
    products: 'data products',
    agents: 'agents',
    kpis: 'KPIs',
    depth: { deep: 'Deep', standard: 'Standard', draft: 'Draft' },
  },
  explorer: {
    title: 'Explorer',
    intro: 'Browse every layer of the warehouse. Every preview and worksheet result goes through the governed query path, so what you see depends on who you are.',
    tree: 'Objects',
    worksheet: 'Worksheet',
    tabs: { preview: 'Preview', columns: 'Columns', ddl: 'DDL', lineage: 'Lineage', quality: 'Quality', governance: 'Governance' },
    rows: 'rows',
    masked: 'masked',
    rowFiltered: 'Row filter applied',
    noRows: 'No rows.',
    column: 'Column',
    type: 'Type',
    nullable: 'Nullable',
    tags: 'Tags',
    term: 'Glossary term',
    masking: 'Masking for you',
    clear: 'Clear',
    pendingFix: 'Masking not attached yet',
    noRules: 'No data quality rules are declared for this object.',
    qualityPhase: 'Rule results and scores arrive with the quality engine (Phase 5). Declared rules:',
    rule: 'Rule',
    dimension: 'Dimension',
    assertion: 'Assertion',
    severity: 'Severity',
    products: 'Data products using this object',
    policies: 'Policies',
    grants: 'Personas entitled',
    history: 'Recent governed access',
    noHistory: 'No governed queries yet.',
    persona: 'Persona',
    purpose: 'Purpose',
    when: 'When',
    upstream: 'Upstream',
    downstream: 'Downstream',
    run: 'Run',
    running: 'Running…',
    presets: 'Presets',
    sqlLabel: 'SQL (read-only SELECT)',
    worksheetIntro: 'Read-only SELECT queries run with your persona’s masking and row filters. Statements that change data are rejected before they run.',
    emptySchema: 'No objects in this schema.',
    displaySql: 'Executed as (Snowflake dialect)',
  },
  semantic: {
    title: 'Semantic views',
    intro: 'Metrics are defined once, here. Every number on every screen — and every agent answer — is compiled from these definitions.',
    metrics: 'metrics',
    tabs: { model: 'Model', metrics: 'Metrics', dimensions: 'Dimensions', verified: 'Verified queries', yaml: 'YAML', playground: 'Playground' },
    tables: 'Tables',
    dimensions: 'Dimensions',
    timeDimensions: 'Time dimensions',
    facts: 'Facts',
    name: 'Name',
    expression: 'Expression',
    unit: 'Unit',
    synonyms: 'Synonyms',
    term: 'Term',
    rules: 'Default rules',
    question: 'Question',
    status: 'Status',
    verifiedBy: 'Verified by',
    products: 'Published by',
    metric: 'Metric',
    by: 'By',
    grain: 'Time grain',
    range: 'Time range',
    filter: 'Filter',
    value: 'Value',
    none: 'None',
    runQuery: 'Run',
    askAgent: 'Ask an agent this',
    generatedSql: 'Generated SQL (Snowflake dialect)',
    ranges: { none: 'All time', 'last-month': 'Last month', 'last-quarter': 'Last quarter', 'last-4-quarters': 'Last 4 quarters', ytd: 'Year to date', 'last-year': 'Last year' },
    rulesApplied: 'Business rules applied',
    pickMetric: 'Pick a metric and press Run.',
  },
  glossary: {
    title: 'Business glossary',
    intro: 'Every governed term, its owner and where it lives — columns, metrics, products and agents.',
    search: 'Filter terms',
    term: 'Term',
    definition: 'Definition',
    formula: 'Formula',
    owner: 'Owner',
    steward: 'Steward',
    status: 'Status',
    cde: 'Critical data element',
    synonyms: 'Synonyms',
    mappings: 'Where it lives',
    columns: 'Columns',
    metrics: 'Metrics',
    products: 'Data products',
    agents: 'Agents',
    dq: 'Data quality rules on mapped columns',
    noDq: 'No DQ rules on the mapped columns.',
  },
  context: {
    title: 'Context',
    intro: 'What agents know beyond the data: instructions, business rules, verified queries, synonyms and policy documents.',
    tabs: { instructions: 'Instructions', rules: 'Business rules', verified: 'Verified queries', synonyms: 'Synonyms', documents: 'Documents' },
    agent: 'Agent',
    kind: 'Type',
    version: 'Version',
    rule: 'Rule',
    applies: 'Machine-applied filter',
    source: 'Source document',
    searchDocs: 'Search documents',
    noHits: 'No matching passages.',
    injection: 'Contains planted prompt-injection text (adversarial testing)',
    term: 'Term',
    synonyms: 'Synonyms',
    mapsTo: 'Maps to',
    search: 'Search',
  },
  ask: {
    title: 'Ask an Agent',
    intro: 'Every number is produced by the governed query path and cited. Refusing is a valid answer.',
    agents: 'Agents',
    anyAgent: 'Let the router choose',
    suggested: 'Suggested questions',
    placeholder: 'Ask a question about your KPIs…',
    send: 'Ask',
    thinking: 'Working…',
    empty: 'Pick a suggested question or type your own.',
    you: 'You',
    routedTo: 'Routed to',
    inspector: 'Answer inspector',
    inspectorEmpty: 'Select an answer to see how it was produced.',
    tabs: { trace: 'Trace', sql: 'SQL', sources: 'Sources', policy: 'Policy' },
    howAnswered: 'How I answered',
    citations: 'Citations',
    confidence: { trusted: 'Trusted', questionable: 'Questionable', unsafe: 'Unsafe' },
    modes: { scripted: 'Scripted', live: 'Live', live_fallback: 'Live→Scripted fallback' },
    kinds: { answer: 'Answer', decline: 'Declined', clarify: 'Clarify', redirect: 'Redirect', help: 'Help' },
    followups: 'Follow-ups',
    askAgent: 'Ask',
    request: 'Request access',
    helpful: 'Helpful',
    notHelpful: 'Not helpful',
    feedbackReason: 'What was wrong?',
    feedbackSend: 'Send feedback',
    feedbackThanks: 'Thanks — your feedback is in the Agent Quality inbox.',
    noSql: 'No query ran for this answer.',
    noPolicies: 'No policies were applied.',
    noSources: 'No sources were used.',
    rows: 'rows',
    viewTable: 'Result table',
    error: 'The agent could not answer right now.',
    liveUnavailable: 'No API key configured: live and auto answer in scripted mode with a fallback badge.',
    toolCalls: 'Tool calls',
    tokens: 'tokens',
    status: { ok: 'Done', skipped: 'Skipped', blocked: 'Blocked' },
  },
  home: {
    heroLabel: 'Ask anything about',
    heroPlaceholder: 'Ask a business question…',
    heroSubmit: 'Ask',
    tiles: 'Headline KPIs',
    target: 'Target',
    band: { in_band: 'In target band', better: 'Better than target', worse: 'Outside target', unknown: 'No value' },
    openInPlayground: 'Open in Semantic Playground',
    theatre: 'Answer Theatre',
    theatrePause: 'Pause',
    theatrePlay: 'Play',
    theatreNext: 'Next',
    counters: { certified: 'Certified products', agents: 'Production agents', kpis: 'KPIs governed', answered: 'Questions answered', quality: 'Avg quality' },
    ticker: 'Activity',
    tickerEmpty: 'No activity yet — ask a question to start.',
    openItems: 'Your open items',
    openItemsEmpty: 'Nothing waiting on you.',
    approvalsWaiting: 'access requests waiting for your approval',
    requestsPending: 'of your access requests are pending',
    constellation: 'Agents and the products they use',
  },
  marketplace: {
    title: 'Marketplace',
    intro: 'Governed data products and the agents built on them — search, compare, request access.',
    tabs: { all: 'All', products: 'Data products', agents: 'Agents', demand: 'Demand', mesh: 'Mesh', compare: 'Compare' },
    search: 'Search products, agents and KPIs',
    searchButton: 'Search',
    filters: 'Filters',
    apply: 'Apply',
    clear: 'Clear',
    any: 'Any',
    facets: { domain: 'Domain', status: 'Status', tier: 'Quality tier', kpi: 'KPI', sensitivity: 'Sensitivity', pattern: 'Consumption', owner: 'Owner' },
    mine: 'Accessible to me',
    hasAgent: 'Has an agent',
    results: 'results',
    noResults: 'Nothing matches. Try fewer filters or another phrase.',
    kpiHits: 'Matching KPIs',
    status: { DRAFT: 'Draft', IN_DEVELOPMENT: 'In development', IN_CERTIFICATION: 'In certification', CERTIFIED: 'Certified', DEPRECATED: 'Deprecated', RETIRED: 'Retired' },
    agentStatus: { PILOT: 'Pilot', CANARY: 'Canary', PRODUCTION: 'Production' },
    access: { Granted: 'Granted', Pending: 'Pending', Requestable: 'Requestable', Restricted: 'Restricted' },
    quality: 'Quality',
    noQuality: 'Not scored',
    freshness: 'Freshness SLA',
    minutes: 'min',
    consumers: 'Consumers',
    agents: 'Agents',
    kpis: 'KPIs',
    products: 'Products',
    costPerAnswer: 'Cost / answer',
    evalTarget: 'Eval target',
    ask: 'Ask',
    open: 'Open',
    compareAdd: 'Compare',
    compareRun: 'Compare selected',
    compareHint: 'Select up to 3 products on the Data products tab, then compare.',
    compareRows: { access: 'Your access', status: 'Status', version: 'Version', owner: 'Owner', quality: 'Quality', freshness: 'Freshness SLA', availability: 'Availability', nullRate: 'Max null rate', kpis: 'KPIs', patterns: 'Consumption', sensitivity: 'Sensitivity', agents: 'Agents' },
    demand: {
      title: 'Demand board',
      intro: 'Products and agents people need that don’t exist yet. Vote, or add a need.',
      vote: 'Vote',
      voted: 'Voted',
      votes: 'votes',
      add: 'Add a need',
      kind: 'Type',
      titleLabel: 'Title',
      description: 'What would it answer?',
      submit: 'Check and submit',
      duplicates: 'This might already exist — try these first:',
      submitAnyway: 'Submit anyway',
      submitted: 'Added to the demand board.',
      intake: 'Start intake',
    },
    mesh: { data: 'Data mesh', agent: 'Agent mesh', select: 'Select a node to see its blast radius.', blast: 'Blast radius', affected: 'Affected' },
  },
  product: {
    tabs: { overview: 'Overview', contract: 'Contract', schema: 'Schema', quality: 'Quality', lineage: 'Lineage', semantic: 'Semantic', consumption: 'Consumption', agents: 'Agents', value: 'Value', history: 'History' },
    purpose: 'Purpose',
    decision: 'Decision supported',
    decider: 'Who decides',
    cadence: 'Cadence',
    workaround: 'Current workaround',
    consequence: 'If it is wrong',
    sampleQuestions: 'Sample questions',
    owner: 'Owner',
    steward: 'Steward',
    stage: 'Lifecycle stage',
    requestAccess: 'Request access',
    downloadContract: 'Download contract (YAML)',
    column: 'Column',
    type: 'Type',
    tags: 'Tags',
    term: 'Glossary term',
    maskingForYou: 'Masking for you',
    clear: 'Clear',
    masked: 'Masked',
    rule: 'Rule',
    dimension: 'Dimension',
    assertion: 'Assertion',
    observed: 'Observed',
    result: 'Result',
    pass: 'Pass',
    fail: 'Fail',
    scoreTrend: 'Score history',
    metrics: 'Metrics',
    verified: 'Verified queries',
    endpoints: 'Endpoints',
    usedBy: 'Agents using this product',
    noAgents: 'No agent uses this product yet.',
    value: 'Value case',
    annualValue: 'Modelled annual value',
    measured: 'Measured',
    assumptions: 'Assumptions',
    noValue: 'No value case recorded.',
    versions: 'Versions',
    historyPending: 'Gate decisions and certifications appear here once the lifecycle engine runs (Product Studio).',
  },
  agentDetail: {
    tabs: { overview: 'Overview', coverage: 'Coverage map', products: 'Products & tools', instructions: 'Instructions', evaluation: 'Evaluation', release: 'Release', usage: 'Usage & cost', try: 'Try it' },
    personas: 'Serves',
    outOfScope: 'Out of scope',
    guardrails: 'Guardrails',
    kpi: 'KPI',
    grains: 'Grains',
    slices: 'Slices',
    depth: 'Depth',
    tools: 'Tools',
    columns: 'Columns',
    evalPending: 'No evaluation run yet — the evaluation harness arrives with Agent Factory.',
    thresholds: 'Publish thresholds',
    release: 'Release state',
    budgets: 'Budgets',
    answers: 'Answers recorded',
    tryIt: 'Ask this agent',
  },
  access: {
    title: 'My Access',
    intro: 'What you can use, what you can answer, and what is waiting on you.',
    products: 'Data products',
    agents: 'Agents',
    coverage: 'Can I answer it?',
    coverageIntro: 'Every KPI in the estate, and whether your entitlements let an agent answer it for you.',
    yes: 'Yes',
    no: 'No',
    via: 'via',
    needs: 'needs',
    pending: 'Your requests',
    noRequests: 'No access requests yet.',
    expires: 'Expires',
    noExpiry: 'No expiry',
    inbox: 'Approvals waiting on you',
    inboxEmpty: 'Nothing waiting on you.',
    approve: 'Approve',
    deny: 'Deny',
    rationale: 'Rationale',
    rationalePlaceholder: 'Why are you approving or denying?',
    request: {
      title: 'Request access',
      purpose: 'Purpose',
      justification: 'Justification',
      justificationPlaceholder: 'What will you use it for?',
      duration: 'Duration',
      days: 'days',
      preview: 'Policy preview',
      auto: 'Approved automatically',
      approvers: 'Required approvers',
      stillMasked: 'Columns that stay masked for you',
      rowFilter: 'Row filter that will apply',
      policies: 'Policies',
      submit: 'Submit request',
      submitted: 'Request submitted',
      granted: 'Access granted',
      cancel: 'Close',
      none: 'None',
    },
    states: { PENDING: 'Pending', GRANTED: 'Granted', DENIED: 'Denied', EXPIRED: 'Expired', REVOKED: 'Revoked' },
  },
  studio: {
    title: 'Product Studio',
    intro: 'The governed lifecycle: agents draft, people decide at every gate.',
    board: 'Board',
    table: 'Table',
    stage: 'Stage',
    proposals: 'open proposals',
    stale: 'stale gate',
    newRequest: 'Request a product',
    gateStates: { PENDING: 'Gate pending', IN_REVIEW: 'In review', APPROVED: 'Approved', REJECTED: 'Rejected', STALE: 'Stale' },
    stages: 'Stages',
    artifacts: 'Artifacts',
    notStarted: 'Not started',
    edit: 'Edit',
    save: 'Commit version',
    cancel: 'Cancel',
    commitMessage: 'Commit message',
    human: 'Human',
    agentAccepted: 'Agent — accepted by',
    agentPanel: 'Agent',
    runAgent: 'Run agent',
    noProposals: 'No open proposals.',
    accept: 'Accept',
    reject: 'Reject',
    editAccept: 'Edit & accept',
    acceptAll: 'Accept all (non-sensitive)',
    criteria: 'Exit criteria',
    gate: 'Gate',
    quorum: 'Quorum',
    requiredRoles: 'Required roles',
    veto: 'Veto',
    evidence: 'Evidence',
    decisions: 'Decisions',
    submit: 'Submit for review',
    approve: 'Approve',
    rejectGate: 'Reject',
    vetoGate: 'Veto',
    rationale: 'Rationale',
    noGate: 'This stage is continuous; the Steward agent monitors it.',
    staleBanner: 'Re-approval needed',
    certification: 'Certification checks',
    evaluate: 'Re-evaluate checks',
    applyFix: 'Apply fix',
    fixApplied: 'Fix applied',
    autopilot: 'Autopilot',
    autopilotStart: 'Start',
    autopilotStep: 'Next step',
    autopilotCancel: 'Cancel',
    autopilotPlay: 'Play',
    autopilotPause: 'Pause',
    speed: 'Speed',
    exports: 'Exports',
    evidencePack: 'Evidence pack (.docx)',
    contract: 'Data contract (ODCS YAML)',
    openLineage: 'OpenLineage (JSON)',
    auditBundle: 'Audit bundle (.zip)',
    runProfiling: 'Run profiling now',
    runDq: 'Run DQ rules now',
    tasks: 'Open tasks',
    status: { pass: 'Pass', warn: 'Warn', fail: 'Fail' },
  },
  intake: {
    title: 'Request a product',
    intro: 'Tell us the decision you are blocked on. We check whether something already answers it.',
    steps: ['Decision', 'Who & how often', 'Questions', 'Stakes & freshness', 'Review'],
    titleLabel: 'Short title',
    decision: 'What decision are you blocked on?',
    decider: 'Who makes the decision?',
    cadence: 'How often?',
    workaround: 'What do you do today instead?',
    questions: 'Questions you would ask (at least three)',
    addQuestion: 'Add question',
    stakes: 'What happens if the decision is wrong?',
    freshness: 'How fresh must the data be?',
    back: 'Back',
    next: 'Next',
    submit: 'Submit request',
    duplicates: 'This might already answer it — try asking:',
    similarity: 'similar',
    submitted: 'Request submitted',
    triage: 'Triage',
    approve: 'Approve → create Draft product',
    merge: 'Merge into',
    decline: 'Decline',
    reason: 'Reason',
    sla: 'Triage SLA due',
    breached: 'SLA breached',
    states: { SUBMITTED: 'Submitted', TRIAGE: 'In triage', APPROVED: 'Approved', MERGED: 'Merged', DECLINED: 'Declined' },
    openProduct: 'Open in Product Studio',
    requests: 'Requests',
    noTriageRole: 'Switch to a product owner or steward persona to triage.',
  },
  outcome: {
    denied: 'Access needed',
    rejected: 'Query not run',
    unavailable: 'Not available yet',
    request: 'Request access',
  },
  errors: {
    notFoundTitle: 'Nothing here',
    notFoundBody: 'This page does not exist in the current demo.',
    backToLauncher: 'Back to the launcher',
  },
} as const;

export type Copy = typeof copy;
