/**
 * Generic UI copy (English). Industry-specific strings never live here — they come from the active pack.
 * Product name is white-label: read it from the active brand, never from this file.
 */
export const copy = {
  doors: {
    home: 'Home',
    consume: 'Consume',
    build: 'Build',
    run: 'Run',
    strategy: 'Strategy',
  },
  nav: {
    home: 'Home',
    marketplace: 'Marketplace',
    ask: 'Ask an Agent',
    access: 'My Access',
    request: 'Request a Product',
    studio: 'Product Studio',
    factory: 'Agent Factory',
    explorer: 'Explorer',
    semantic: 'Semantic',
    glossary: 'Glossary',
    context: 'Context',
    health: 'Health',
    agentQuality: 'Agent Quality',
    costValue: 'Cost & Value',
    impact: 'Impact',
    audit: 'Audit & Lineage',
    platformMap: 'Platform Map',
    knockout: 'Knockout',
    compare: 'Compare',
    readiness: 'Readiness',
    roadmap: 'Roadmap',
    portfolio: 'Portfolio',
    operatingModel: 'Operating Model',
    admin: 'Admin',
  },
  navDetail: {
    productDetail: 'Data product',
    agentDetail: 'Agent',
    requestDetail: 'Product request',
    studioWorkspace: 'Product workspace',
    factoryDraft: 'Agent draft',
  },
  shell: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary',
    packSwitcher: 'Switch industry pack',
    searchPlaceholder: 'Search',
    searchShortcut: '/',
    paletteShortcut: 'Ctrl K',
    persona: 'Persona',
    personaPending: 'Demo personas come from the active pack (Phase 2).',
    presenterMenu: 'Presenter menu',
    presenterPending: 'Presenter tools arrive in Phase 9.',
    footer: 'Synthetic demo data',
    asOf: 'as of',
    modes: { scripted: 'Scripted', live: 'Live', auto: 'Auto' },
    modeLabel: 'Agent mode',
  },
  stub: {
    eyebrow: 'Coming in phase',
    module: 'Module',
    spec: 'Specification',
    params: 'Route parameters',
    none: 'none',
    body: 'This screen is scaffolded. Its behaviour and acceptance criteria are defined in the specification and land in the phase shown.',
  },
  launcher: {
    title: 'Demo launcher',
    subtitle: 'Pick an industry pack, brand it for the client and choose a story.',
    noPacks: 'No industry packs are installed yet.',
    noPacksHint: 'Packs are converted from the predecessor prototypes in Phase 1. Until then you can browse the empty shell.',
    openShell: 'Open the empty shell',
  },
  errors: {
    notFoundTitle: 'Nothing here',
    notFoundBody: 'This page does not exist in the current demo.',
    backToLauncher: 'Back to the launcher',
  },
} as const;

export type Copy = typeof copy;
