/**
 * Snowflake deploy bundle (12-deployment §6, ADR-0025). A pack is deployed as **data**, not as transforms:
 * every object of the built DuckDB warehouse (Bronze, Silver, Gold and the generated layers, views
 * included) is exported to Parquet and loaded into a plain Snowflake table of the same name. Snowflake
 * therefore holds exactly the rows the golden answers were recorded on, and the pack's DuckDB-dialect
 * transforms never need translating.
 *
 * The bundle (`deploy.sql`, `verify.sql`, `data/*.parquet`, `manifest.json`) runs with SnowSQL, because
 * `PUT` is not available over the SQL API:
 *
 *   cd <bundle> && snowsql -f deploy.sql && snowsql -f verify.sql
 *
 * The SQL is deterministic: there are no timestamps, and objects are in sorted order.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Pack } from '@/lib/packs/schema';
import { openWarehouseReadOnly } from './build';
import { exportParquet } from './duckdb';
import { LAYER_SCHEMAS, MASKING_MACROS } from './layout';

export interface BundleObject {
  fqn: string;
  rows: number;
  file: string;
  columns: { name: string; duckdbType: string; snowflakeType: string }[];
}

export interface SnowflakeBundle {
  dir: string;
  database: string;
  objects: BundleObject[];
}

const SCHEMAS = Object.values(LAYER_SCHEMAS);
const ident = /^[A-Za-z_][A-Za-z0-9_]*$/;

/** DuckDB column type → Snowflake type. Unknown types fail loudly rather than load wrongly. */
export function snowflakeType(duckdb: string): string {
  const t = duckdb.toUpperCase();
  if (t === 'VARCHAR' || t.startsWith('VARCHAR(')) return 'VARCHAR';
  if (['TINYINT', 'SMALLINT', 'INTEGER', 'BIGINT', 'HUGEINT', 'UTINYINT', 'USMALLINT', 'UINTEGER', 'UBIGINT'].includes(t)) return 'NUMBER(38,0)';
  if (t === 'DOUBLE' || t === 'FLOAT' || t === 'REAL') return 'FLOAT';
  const dec = /^DECIMAL\((\d+),\s*(\d+)\)$/.exec(t);
  if (dec) return `NUMBER(${dec[1]},${dec[2]})`;
  if (t === 'BOOLEAN') return 'BOOLEAN';
  if (t === 'DATE') return 'DATE';
  if (t === 'TIMESTAMP' || t === 'TIMESTAMP_NS' || t === 'TIMESTAMP_MS') return 'TIMESTAMP_NTZ';
  throw new Error(`No Snowflake mapping for DuckDB type ${duckdb}`);
}

/** Export expression per column: HUGEINT (Parquet has no 128-bit int) as DECIMAL(38,0). */
function exportExpr(name: string, duckdbType: string): string {
  const q = `"${name.replace(/"/g, '""')}"`;
  return duckdbType.toUpperCase() === 'HUGEINT' ? `CAST(${q} AS DECIMAL(38,0)) AS ${q}` : q;
}

const sqlString = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Snowflake reserved words (cannot be unquoted column names). */
const RESERVED = new Set(
  ('ACCOUNT ALL ALTER AND ANY AS BETWEEN BY CASE CAST CHECK COLUMN CONNECT CONNECTION CONSTRAINT CREATE CROSS CURRENT ' +
    'CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER DATABASE DELETE DISTINCT DROP ELSE EXISTS FALSE FOLLOWING FOR ' +
    'FROM FULL GRANT GROUP GSCLUSTER HAVING ILIKE IN INCREMENT INNER INSERT INTERSECT INTO IS ISSUE JOIN LATERAL LEFT LIKE ' +
    'LOCALTIME LOCALTIMESTAMP MINUS NATURAL NOT NULL OF ON OR ORDER ORGANIZATION QUALIFY REGEXP REVOKE RIGHT RLIKE ROW ROWS ' +
    'SAMPLE SCHEMA SELECT SET SOME START TABLE TABLESAMPLE THEN TO TRIGGER TRUE TRY_CAST UNION UNIQUE UPDATE USING VALUES ' +
    'VIEW WHEN WHENEVER WHERE WITH').split(' '),
);

/** Column name as created in Snowflake: unquoted, or quoted in upper case when reserved (same resolution). */
export function snowflakeColumn(name: string): string {
  return RESERVED.has(name.toUpperCase()) ? `"${name.toUpperCase()}"` : name;
}

/** Masking macros as Snowflake SQL UDFs (same semantics; REGEXP_REPLACE replaces all matches by default). */
export function maskingFunctions(): string[] {
  return Object.entries(MASKING_MACROS).map(([name, body]) => {
    const sf = body.replace(/,\s*'g'\)/g, ')');
    return `CREATE OR REPLACE FUNCTION GOVERNANCE.${name.toUpperCase()}(V VARCHAR) RETURNS VARCHAR AS $$ ${sf} $$;`;
  });
}

function comment(pack: Pack, fqn: string): string {
  const [schema = '', name = ''] = fqn.split('.');
  if (schema === 'RAW_BRONZE') return pack.sources.find((s) => s.name === name)?.description ?? '';
  return pack.objects.find((o) => o.fqn === fqn)?.description ?? '';
}

export function renderDeploySql(pack: Pack, objects: BundleObject[]): string {
  const db = pack.manifest.database;
  const lines = [
    `-- Snowflake deploy for pack ${pack.manifest.id} (${pack.manifest.company.name}). Synthetic demo data.`,
    '-- Generated by `pnpm snowflake:bundle`; run with SnowSQL from the bundle directory: snowsql -f deploy.sql',
    `CREATE DATABASE IF NOT EXISTS ${db};`,
    // The governed path quotes lower-case identifiers; tables use unquoted (upper-case) names.
    `ALTER DATABASE ${db} SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;`,
    `USE DATABASE ${db};`,
    ...SCHEMAS.map((s) => `CREATE SCHEMA IF NOT EXISTS ${s};`),
    'CREATE OR REPLACE FILE FORMAT GOVERNANCE.KEYSTONE_PARQUET TYPE = PARQUET;',
    'CREATE OR REPLACE STAGE GOVERNANCE.KEYSTONE_LOAD FILE_FORMAT = GOVERNANCE.KEYSTONE_PARQUET;',
    `CREATE OR REPLACE FUNCTION GOVERNANCE.AS_OF() RETURNS DATE AS $$ DATE ${sqlString(pack.manifest.asOf)} $$;`,
    ...maskingFunctions(),
    '',
  ];
  for (const o of objects) {
    const cols = o.columns.map((c) => `  ${snowflakeColumn(c.name)} ${c.snowflakeType}`).join(',\n');
    const stage = `@GOVERNANCE.KEYSTONE_LOAD/${o.fqn}`;
    lines.push(
      `CREATE OR REPLACE TABLE ${o.fqn} (\n${cols}\n) COMMENT = ${sqlString(comment(pack, o.fqn))};`,
      `PUT file://data/${o.fqn}.parquet ${stage} AUTO_COMPRESS = FALSE OVERWRITE = TRUE;`,
      `COPY INTO ${o.fqn} FROM ${stage} FILE_FORMAT = (FORMAT_NAME = 'GOVERNANCE.KEYSTONE_PARQUET') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;`,
      '',
    );
  }
  return `${lines.join('\n')}\n`;
}

/** One row per object: expected vs loaded row count. Every `ok` must be TRUE. */
export function renderVerifySql(pack: Pack, objects: BundleObject[]): string {
  const rows = objects.map((o) => `SELECT ${sqlString(o.fqn)} AS object, ${o.rows} AS expected, (SELECT COUNT(*) FROM ${o.fqn}) AS loaded, loaded = expected AS ok`);
  return `USE DATABASE ${pack.manifest.database};\n${rows.join('\nUNION ALL\n')}\nORDER BY ok, object;\n`;
}

/** Exports the built warehouse at `warehousePath` and writes the bundle into `outDir` (replaced). */
export async function buildSnowflakeBundle(pack: Pack, warehousePath: string, outDir: string): Promise<SnowflakeBundle> {
  const w = await openWarehouseReadOnly(warehousePath);
  let objects: Omit<BundleObject, 'rows' | 'file'>[];
  try {
    const list = SCHEMAS.map(sqlString).join(', ');
    const tables = await w.query(`SELECT table_schema, table_name FROM information_schema.tables WHERE table_schema IN (${list}) ORDER BY table_schema, table_name`);
    const cols = await w.query(`SELECT table_schema, table_name, column_name, data_type FROM information_schema.columns WHERE table_schema IN (${list}) ORDER BY table_schema, table_name, ordinal_position`);
    objects = tables.rows.map(([s, t]) => {
      const fqn = `${String(s)}.${String(t)}`;
      const columns = cols.rows
        .filter((c) => c[0] === s && c[1] === t)
        .map((c) => {
          const name = String(c[2]);
          if (!ident.test(name)) throw new Error(`${fqn}.${name}: column name is not a plain identifier`);
          return { name, duckdbType: String(c[3]), snowflakeType: snowflakeType(String(c[3])) };
        });
      return { fqn, columns };
    });
  } finally {
    await w.close();
  }
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, 'data'), { recursive: true });
  const exported = await exportParquet(
    warehousePath,
    objects.map((o) => ({ select: `SELECT ${o.columns.map((c) => exportExpr(c.name, c.duckdbType)).join(', ')} FROM ${o.fqn}`, file: join(outDir, 'data', `${o.fqn}.parquet`) })),
  );
  const full: BundleObject[] = objects.map((o, i) => ({ ...o, rows: exported[i]?.rows ?? 0, file: `data/${o.fqn}.parquet` }));
  writeFileSync(join(outDir, 'deploy.sql'), renderDeploySql(pack, full));
  writeFileSync(join(outDir, 'verify.sql'), renderVerifySql(pack, full));
  const manifest = { pack: pack.manifest.id, database: pack.manifest.database, objects: full.map(({ fqn, rows, file, columns }) => ({ fqn, rows, file, columns: columns.map((c) => ({ name: c.name, type: c.snowflakeType })) })) };
  writeFileSync(join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return { dir: outDir, database: pack.manifest.database, objects: full };
}
