/**
 * pnpm db:pg:prepare — renders prisma/postgres/schema.prisma (provider = postgresql) from the SQLite schema and
 * generates the client for it (ADR-0010). Apply with `pnpm db:pg:push`, then `pnpm db:seed`, using a
 * postgresql:// DATABASE_URL. Snapshot reset is SQLite-only (ADR-0021).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const src = readFileSync(join(process.cwd(), 'prisma', 'schema.prisma'), 'utf8');
const out = src.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
if (out === src) throw new Error('prisma/schema.prisma does not declare provider = "sqlite"');
mkdirSync(join(process.cwd(), 'prisma', 'postgres'), { recursive: true });
writeFileSync(join(process.cwd(), 'prisma', 'postgres', 'schema.prisma'), `// GENERATED by scripts/db-provider.ts from prisma/schema.prisma — do not edit.\n${out}`);
console.log('prisma/postgres/schema.prisma written (provider = postgresql).');
